- name: install cron job (ansible-pull)
  cron:
    user: ansible
    name: "ansible managed: Ansible Pull"
    hour: "*/2"
    job: "/usr/bin/ansible-pull -U https://github.com/kcgaisford/plex_ansible"
